# Generated by Django 5.0 on 2024-01-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
