# Generated by Django 5.0 on 2024-01-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvManager', '0002_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
